language: android
jdk: oraclejdk8
sudo: false

addons:
  apt:
    packages:
      - lynx

android:
 licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
 components:
  - tools
  - platform-tools

  - android-27
  - build-tools-28-rc1
  - add-on
  - extra

script:
    - ./gradlew build check
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
before_install:
      - chmod +x ./gradlew
      - yes | sdkmanager "platforms;android-27"
      - yes | sdkmanager "build-tools;28.0.0-rc1"